# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:           Misc Projects
tagline:         'avh misc projects'
description:     "Misc projects"
url:          	 avonholle.github.io/misc-grad-school
baseurl:		     /misc-grad-school/

author:
  name:          'Ann Von Holle'

github:
  repo:           https://github.com/avonholle/misc-grad-school